Fix duplicate declarations
Error: cannot define PHPMailer/PHPMailer/PHPMailer because it already exists in libphp_phpmailer folder.
Changed require to require_once.
Also changed typo in php variables.